# Generated by Django 5.0.6 on 2024-05-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='description',
            new_name='storyline',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='watchlist_app.streamplatform'),
            preserve_default=False,
        ),
    ]
